<div class="container-fluid ">
    <div class="row mt-5 mx-auto text-center">
        <div class="col">
           <div class="row my-2">
               <div class="container mx-auto">
                   <h4>Horarios</h4>
                   <button class="btn bg-info">Marcar Horario</button>
               </div>
           </div>

           <div class="row">
                 <div class="card mx-auto my-2">
                     <div class="card-body">
                         <p>nome:</p>
                         <p>horario:</p>
                         <p>atendimento:</p>
                         <button class="btn btn-lg btn-info">Detalhes</button>
                         <button class="btn btn-lg btn-danger">Cancelar</button>
                     </div>
                 </div>

           </div>
        </div>
        <div class="col bg-info mx-2">
            <h1>Clientes</h1>
        </div>
    </div>
</div>